---
# We have an immutable 'apt_key' variable from the loop

- name: 'apt:key:content'
  when: "'content' in apt_key"
  block:
    - name: 'apt:key:content:instance'
      ansible.builtin.set_fact:
        apt_key_instance: "{{ apt_key_defaults_content | combine(apt_key) }}"

    # We have a mutable 'apt_key_instance' variable with defaults

    - name: 'apt:key:content:content'
      ansible.builtin.set_fact:
        apt_key_content: "{{ apt_key_instance.content }}"
        apt_key_instance: "{{ apt_key_instance | dict2items | rejectattr('key', 'equalto', 'content') | items2dict }}"

    # We have 'apt_key_content' extracted from 'apt_key_instance'

    - name: 'apt:key:content:template'
      ansible.builtin.template: "{{ apt_key_instance }}"
      vars:
        apt_key_content: "{{ apt_key_content }}"
      tags:
        - 'skip_ansible_lint'

- name: 'apt:key:download'
  when: "'content' not in apt_key"
  block:
    - name: 'apt:key:download:instance'
      ansible.builtin.set_fact:
        apt_key_instance: "{{ apt_key_defaults_download | combine(apt_key) }}"

    # We have a mutable 'apt_key_instance' variable with defaults

    - name: 'apt:key:download:download'
      ansible.builtin.get_url: "{{ apt_key_instance }}"
      tags:
        - 'skip_ansible_lint'
