---
# We have an immutable 'apt_source' variable from the loop

- name: 'apt:source:instance'
  ansible.builtin.set_fact:
    apt_source_instance: "{{ apt_source_defaults | combine(apt_source) }}"

# We have a mutable 'apt_source_instance' variable with defaults

- name: 'apt:source:content'
  ansible.builtin.set_fact:
    apt_source_content: "{{ apt_source_content_default | combine(apt_source_instance.content) }}"
    apt_source_instance: "{{ apt_source_instance | dict2items | rejectattr('key', 'equalto', 'content') | items2dict }}"

# We have 'apt_source_content' extracted from 'apt_source_instance' with defaults

- name: 'apt:source:template'
  ansible.builtin.template: "{{ apt_source_instance }}"
  vars:
    apt_source_content: "{{ apt_source_content }}"
  tags:
    - 'skip_ansible_lint'
