---
- name: 'apt:keys:basepath'
  ansible.builtin.file: "{{ apt_keys_basepath }}"
  tags:
    - 'skip_ansible_lint'

- name: 'apt:auths:basepath'
  ansible.builtin.file: "{{ apt_auths_basepath }}"
  tags:
    - 'skip_ansible_lint'

- name: 'apt:sources:basepath'
  ansible.builtin.file: "{{ apt_sources_basepath }}"
  tags:
    - 'skip_ansible_lint'

- name: 'apt:preferences:basepath'
  ansible.builtin.file: "{{ apt_preferences_basepath }}"
  tags:
    - 'skip_ansible_lint'

- name: 'apt:keys:remove'
  loop: '{{ apt_keys }}'
  loop_control:
    loop_var: 'apt_key'
  when: "(apt_key.state | default('present') == 'absent')"
  ansible.builtin.file:
    path: '{{ apt_key.path }}'
    state: 'absent'
  notify:
    - 'apt:update_cache'

- name: 'apt:auths:remove'
  loop: '{{ apt_auths }}'
  loop_control:
    loop_var: 'apt_auth'
  when: "(apt_auth.state | default('present') == 'absent')"
  ansible.builtin.file:
    path: '{{ apt_auth.path }}'
    state: 'absent'
  notify:
    - 'apt:update_cache'

- name: 'apt:sources:remove'
  loop: '{{ apt_sources }}'
  loop_control:
    loop_var: 'apt_source'
  when: "(apt_source.state | default('present') == 'absent')"
  ansible.builtin.file:
    path: '{{ apt_source.path }}'
    state: 'absent'
  notify:
    - 'apt:update_cache'

- name: 'apt:preferences:remove'
  loop: '{{ apt_preferences }}'
  loop_control:
    loop_var: 'apt_preference'
  when: "(apt_preference.state | default('present') == 'absent')"
  ansible.builtin.file:
    path: '{{ apt_preference.path }}'
    state: 'absent'
  notify:
    - 'apt:update_cache'

- name: 'apt:keys:configure'
  loop: '{{ apt_keys }}'
  loop_control:
    loop_var: 'apt_key'
  when: "(apt_key.state | default('present') == 'present')"
  ansible.builtin.include_tasks: './apt_key_configure.yaml'

- name: 'apt:auths:configure'
  loop: '{{ apt_auths }}'
  loop_control:
    loop_var: 'apt_auth'
  when: "(apt_auth.state | default('present') == 'present')"
  ansible.builtin.include_tasks: './apt_auth_configure.yaml'

- name: 'apt:sources:configure'
  loop: '{{ apt_sources }}'
  loop_control:
    loop_var: 'apt_source'
  when: "(apt_source.state | default('present') == 'present')"
  ansible.builtin.include_tasks: './apt_source_configure.yaml'

- name: 'apt:preferences:configure'
  loop: '{{ apt_preferences }}'
  loop_control:
    loop_var: 'apt_preference'
  when: "(apt_preference.state | default('present') == 'present')"
  ansible.builtin.include_tasks: './apt_preference_configure.yaml'
