---
- name: 'apt:keys:remove'
  loop: '{{ apt_keys }}'
  loop_control:
    loop_var: 'apt_key'
  when: "(apt_key.state | default('present') == 'absent')"
  ansible.builtin.include_tasks: './apt_key_remove.yaml'

- name: 'apt:auths:remove'
  loop: '{{ apt_auths }}'
  loop_control:
    loop_var: 'apt_auth'
  when: "(apt_auth.state | default('present') == 'absent')"
  ansible.builtin.include_tasks: './apt_auth_remove.yaml'

- name: 'apt:sources:remove'
  loop: '{{ apt_sources }}'
  loop_control:
    loop_var: 'apt_source'
  when: "(apt_source.state | default('present') == 'absent')"
  ansible.builtin.include_tasks: './apt_source_remove.yaml'

- name: 'apt:preferences:remove'
  loop: '{{ apt_preferences }}'
  loop_control:
    loop_var: 'apt_preference'
  when: "(apt_preference.state | default('present') == 'absent')"
  ansible.builtin.include_tasks: './apt_preference_remove.yaml'

- name: 'apt:keys:configure'
  loop: '{{ apt_keys }}'
  loop_control:
    loop_var: 'apt_key'
  when: "(apt_key.state | default('present') == 'present')"
  ansible.builtin.include_tasks: './apt_key_configure.yaml'

- name: 'apt:auths:configure'
  loop: '{{ apt_auths }}'
  loop_control:
    loop_var: 'apt_auth'
  when: "(apt_auth.state | default('present') == 'present')"
  ansible.builtin.include_tasks: './apt_auth_configure.yaml'

- name: 'apt:sources:configure'
  loop: '{{ apt_sources }}'
  loop_control:
    loop_var: 'apt_source'
  when: "(apt_source.state | default('present') == 'present')"
  ansible.builtin.include_tasks: './apt_source_configure.yaml'

- name: 'apt:preferences:configure'
  loop: '{{ apt_preferences }}'
  loop_control:
    loop_var: 'apt_preference'
  when: "(apt_preference.state | default('present') == 'present')"
  ansible.builtin.include_tasks: './apt_preference_configure.yaml'
